### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by TeoTN** [ryanhornberger/nunjucks-html-loader#3]
Nunjucks-html-loader uses outdated packages:

```
└─┬ nunjucks-html-loader@1.0.0
  └─┬ nunjucks@1.3.4
    └─┬ chokidar@0.12.6
      └─┬ readdirp@1.3.0
        └── graceful-fs@2.0.3
```

which is a problem, since:

`npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.`

Please, update it. Current nunjucks version is 2.4.2 and nunjucks-loader 2.4.3...

**Comment by jeremyzahner** [comment]
@TeoTN This should be resolved. I'm closing the issue. Feel free to reopen if something isn't resolved in your opinion.
