### ISSUE TITLE
Let's publish 1.1.0 to npm

### ISSUE THREAD

**Issue by revelt** [ryanhornberger/nunjucks-html-loader#5]
Hi!

Let's publish 1.1.0 to npm. It's still 1.0.0 there.
If you need any help I'm happy to contribute.

cheers
Roy

**Comment by revelt** [comment]
Closing.

**Comment by jeremyzahner** [comment]
@revelt The package has been bumped on npm. =)

**Comment by revelt** [comment]
I saw your comment and closed it within some seconds :) Thanks for publishing; I'll need it very soon, moving my builds to webpack..

**Comment by jeremyzahner** [comment]
@revelt Do it! Wouldn't want to go back anymore. You should recognize (just in case you missed it) that this loader is particularly for Nunjucks --> HTML and not for Actual Nunjucks --> JS loading.

**Comment by revelt** [comment]
Exactly! I hit the wall with Gulp+BrowserSync, it's crashy and too slow on many templates. React apps on webpack load quicker than my html template builds on Gulp and BrowserSync.. I have huge hopes for this.
